# Use ubuntu as a parent image
FROM ubuntu:24.04

ARG DEBIAN_FRONTEND=noninteractive

# Install the packages we need to build fitbenchmarking
RUN apt-get update && apt-get install -y \
    git \
    sudo \
    cmake \
    ninja-build \
    mpich \
    curl \
    apt-utils

# use uv to manage python version
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
RUN $HOME/.local/bin/uv python install 3.12

# set up a venv to stop python/python3 sillyness
ENV VIRTUAL_ENV=/opt/venv
RUN $HOME/.local/bin/uv venv --seed $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

RUN pip install wheel
RUN pip install "pytest>3.6" \
    pytest-cov \
    coveralls \
    "coverage~=4.5.4" \ 
    urllib3 \
    mock \
    meson \
    "numpy<2.0"

WORKDIR /

##############################################################
# Update cmake -- kitware hosts 3.22 where ubuntu hosts 3.16 #
# (follows instructions on apt.kitware.com)                  #
##############################################################
RUN curl https://apt.kitware.com/kitware-archive.sh | sh -s -- noble

RUN sudo apt-get install -y cmake


###########
# Sscanss #
###########

WORKDIR /

RUN git clone --depth 1 https://github.com/ISISNeutronMuon/SScanSS-2.git
WORKDIR /SScanSS-2
RUN python -m pip install --no-binary=h5py h5py
RUN pip install .

WORKDIR /

#################
# Install pygsl #
#################

RUN apt-get update && \
 apt-get install -y gsl-bin \
 libgsl-dev \
 libgsl-dbg

##################
# Install RALFit #
##################
RUN apt-get install -y gfortran \
    lcov \
    libblas-dev \
    liblapack-dev \
    libgdal-dev

RUN git clone --depth 1 https://github.com/ralna/RALFit

RUN mkdir -p /RALFit-build
WORKDIR /RALFit-build

ENV CC=gcc
RUN cmake /RALFit/libRALFit && make && make install

# make install for RALFit doesn't work in a container, so manually pip install
RUN pip install .

ENV LD_LIBRARY_PATH=/RALFit-build/src:$LD_LIBRARY_PATH
RUN rm -rf /RALFit/libRALFit/

################
# Build cutest #
################

RUN mkdir -p /cutest

WORKDIR /cutest

RUN git clone --depth 1 https://github.com/ralna/ARCHDefs ./archdefs && \
    git clone --depth 1 https://github.com/ralna/SIFDecode ./sifdecode && \
    git clone --depth 1 https://github.com/ralna/CUTEst ./cutest

RUN mkdir pycutest_cache

ENV ARCHDEFS=/cutest/archdefs/ \
    SIFDECODE=/cutest/sifdecode/ \
    MASTSIF=/home/fitbenchmarking/examples/benchmark_problems/SIF/ \
    CUTEST=/cutest/cutest/ \
    MYARCH="pc64.lnx.gfo" \
    PYCUTEST_CACHE=/cutest/pycutest_cache/

ENV PYTHONPATH="${PYCUTEST_CACHE}:${PYTHONPATH}"

# Install sifdecode

WORKDIR $SIFDECODE
RUN printf "1\n1\nn" > sifdecode.input && \
    printf "1\nny" >> sifdecode.input && \
    ./install_sifdecode  < sifdecode.input

# Install cutest
WORKDIR $CUTEST
RUN meson setup builddir
RUN meson compile -C builddir
RUN meson install -C builddir
RUN mkdir -p objects/pc64.lnx.gfo/single
RUN mkdir -p objects/pc64.lnx.gfo/double
RUN ln -s /usr/local/lib/libcutest_single.a objects/pc64.lnx.gfo/single/libcutest.a
RUN ln -s /usr/local/lib/libcutest_double.a objects/pc64.lnx.gfo/double/libcutest.a

# install pycutest
RUN python -m pip install pycutest

##################
# Install Mantid #
##################

WORKDIR /
RUN apt-get -y install libjemalloc-dev libmuparser-dev libjsoncpp-dev libeigen3-dev xfonts-scalable libocct-data-exchange-dev libocct-draw-dev libocct-foundation-dev libocct-modeling-algorithms-dev libocct-modeling-data-dev libocct-ocaf-dev libocct-visualization-dev libboost-all-dev libpoco-dev libtbb-dev
RUN pip install versioningit

# Requires NeXuS format
RUN wget -O nexus.tar.gz https://github.com/nexusformat/code/archive/refs/tags/v4.4.3.tar.gz
RUN tar --no-same-owner --no-same-permissions -xzf nexus.tar.gz
RUN mv code-4.4.3 nexus
RUN mkdir nexus/build
WORKDIR /nexus-build
RUN cmake -G Ninja /nexus -DCMAKE_BUILD_TYPE=Release -DENABLE_CXX=ON
RUN cmake --build .
RUN cmake --install .
RUN rm -rf /nexus

ARG MANTID_VERSION=6.10.0

WORKDIR /
RUN git clone -b "v$MANTID_VERSION" --depth 1 https://github.com/mantidproject/mantid.git 
COPY mantid.patch /
WORKDIR /mantid
RUN git apply ../mantid.patch
RUN mv /mantid /mantid-$MANTID_VERSION

RUN mkdir -p /opt/Mantid
WORKDIR /opt/Mantid
RUN cmake -G Ninja /mantid-$MANTID_VERSION -DENABLE_MANTIDQT=OFF -DENABLE_WORKBENCH=OFF -DENABLE_DOCS=OFF -DENABLE_PRECOMMIT=OFF
RUN cmake --build .

ENV PYTHONPATH=$PYTHONPATH:/opt/Mantid/lib:/opt/Mantid/bin
RUN python -m pip install --no-binary=h5py IPython six python-dateutil pyyaml h5py
ENV HDF5_DISABLE_VERSION_CHECK=2
RUN /opt/Mantid/bin/mantidpython -m  mantid.simpleapi || echo "expected segfault on first run"

WORKDIR /

#################
# install pygsl #
#################

WORKDIR /

RUN apt-get -y install swig
RUN wget -O pygsl.tar.gz https://github.com/pygsl/pygsl/archive/refs/tags/v2.4.0.tar.gz
RUN tar --no-same-owner --no-same-permissions -xzf pygsl.tar.gz

WORKDIR /pygsl-2.4.0
RUN python -m pip install .

#################
# Install Ceres #
#################
WORKDIR /

RUN sudo apt-get install -y libgoogle-glog-dev \
 libgflags-dev \
 libatlas-base-dev \
 libsuitesparse-dev \
 libeigen3-dev \
 libtbb-dev

# Make ceres directory 
RUN mkdir -p /ceres
# Change working directory to ceres  
WORKDIR /ceres 
# Download ceres solver 2.0.0 tar 
RUN wget http://ceres-solver.org/ceres-solver-2.2.0.tar.gz
# unpack the tar file 
RUN tar --no-same-owner --no-same-permissions -xzf ceres-solver-2.2.0.tar.gz
# Make ceres-bin directory
RUN mkdir -p ceres-bin 
# Change working directory to ceres-bin
WORKDIR /ceres/ceres-bin
RUN cmake -G Ninja ../ceres-solver-2.2.0
RUN cmake --build .
RUN cmake --install .
RUN rm -rf ../ceres-solver-2.2.0

WORKDIR /
ENV CXX=g++
RUN git clone --depth 1 https://github.com/cvg/pyceres.git
WORKDIR /pyceres
RUN python -m pip install .

WORKDIR /


###########
# Theseus #
###########

WORKDIR /

RUN apt-get install libsuitesparse-dev

# Install pytorch
RUN pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cpu

# Install theseus
RUN pip install theseus-ai

WORKDIR /


###########
# Tidy up #
###########
RUN apt -y autoremove

## ALL SET UP ##
WORKDIR /home/
