name: 'PyPI'

on:
  schedule:
    - cron: '0 9 * * 1'

jobs:
  package_install_check:
    name: Package install check
    if: github.event.repository.fork == false
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13]
        python: ['3.9', '3.13']
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python }}
        check-latest: true
    - name: Pip install fitbenchmarking (Linux/macOS)
      if: matrix.os != 'windows-latest'
      run: |
        echo "setuptools<78.0.0" > /tmp/constraints.txt
        pip install fitbenchmarking[bumps,DFO,gradient-free,minuit,SAS,numdifftools,lmfit]
      env:
        PIP_CONSTRAINT: /tmp/constraints.txt
    - name: Pip install fitbenchmarking (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        powershell -Command "Set-Content -Path 'C:\temp\constraints.txt' -Value 'setuptools<78.0.0'"
        pip install fitbenchmarking[bumps,DFO,gradient-free,minuit,SAS,numdifftools,lmfit]
      env:
        PIP_CONSTRAINT: C:\temp\constraints.txt